### PR TITLE
Upgrade to NHibernate 5.1.0

### LINKED ISSUE #1: Upgrade to NH5 etc
Hi,

Found this via your blog post from a few years ago. Looks like a brilliant extension to NH. Hope it will solve my issues with calculated properties.

With the last commit being 4 years ago, this doesn't work with NH5. I'm prepared to submit some PRs. Would also like to get this working on .NET Core. Just checking in with you first that you're willing to review the PRs and maybe help with some compatibility issues, as I'm not an expression with expressions and query providers. But I'll attempt the bulk of the effort. I'll also assist in getting this on NuGet if that's OK with you.

Let me know if you're OK with this.

thanks

### PR DESCRIPTION
**Pull request by igitur**
Hi,

This PR adds a number of changes. If accepted, I suggest you rebase onto `master` and not merge.

I think the commit history is quite clear, but please let me know if you have any feedback or questions.

Fixes #1

### CODE REVIEW

**Comment by igitur** [comment]
I've also published this under https://www.nuget.org/packages/NHibernate.Property.Expressions/1.1.0-beta1

I would gladly add you as owner if you want.

**Comment by andersthorsen** [comment]
Thanks! I will look at this next week. A quick glance at the  commit history, it looks quite nice tough :)

**Comment by andersthorsen** [comment]
Thanks for the work! The changes look good too me and I'll merge the request as long as the license is ok with you.

As it's published as a NuGet I wanted to add a license so I've added a MIT license file to the repository. Let me know if that ok to you, seeing as there was no LICENSE file when the patch was made.

Also, please add my NuGet handle anders_to to the package.

**Comment by igitur** [comment]
MIT works for me.

**Pull request merged**
